global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "worker"
    static_configs:
      - targets: ["worker:9090"]
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]
